### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by yosun** [One-2-3-45/One-2-3-45#1]
Please provide details on benchmarks. Which hardware setup are you using for benchmarking 45s

**Comment by Colin97** [comment]
Hello, the 45s runtime is reported on a single A100 GPU.
Specifically, our 3D reconstruction module reconstructs a 3D mesh in approximately 5 seconds, with the remaining time primarily spent on Zero123 predictions, which take roughly 1 second per image on an A100 GPU.
