### ISSUE TITLE
i LIKE Your video styles may I ask which app you are using to generate it? Thank you!

### ISSUE THREAD

**Issue by yuchenlichuck** [One-2-3-45/One-2-3-45#13]
rt

**Comment by yuchenlichuck** [comment]
The video that  you visualize all the generated images

**Comment by Colin97** [comment]
We render each frame and then use ffmpeg to convert the images to video. When generating each frame, we manually tile the images and calculates the offset.

**Comment by yuchenlichuck** [comment]
Oh, sounds like it takes sometimes to generate this beautiful visualization. Thank you for your response
