### ISSUE TITLE
I found the result about human generation, is not that good, what could be the reasons?

### ISSUE THREAD

**Issue by yuchenlichuck** [One-2-3-45/One-2-3-45#14]
![image](https://github.com/One-2-3-45/One-2-3-45/assets/38585175/b9ba80ba-15df-4548-9233-13bf0bd0c6e6)
What could be the reason?

**Comment by xuanlinli17** [comment]
We didn't train on human generation datasets.

**Comment by yuchenlichuck** [comment]
Thank you for your responeses
