### ISSUE TITLE
coordination system used in one-2-3-45

### ISSUE THREAD

**Issue by florinshen** [One-2-3-45/One-2-3-45#17]
great work! but may i ask what world coordination is used in your code when generate the pose ?

It seems not a typical right-hand system adopted in OpenGL

https://github.com/One-2-3-45/One-2-3-45/blob/3c82aa614fcb80924fddd14531056eda7e795aaa/utils/utils.py#L80

**Comment by Colin97** [comment]
We used the OpenCV coordinate frame. The function `calc_pose` computes the Cartesian coordinates (in world frame) of a camera on a sphere from the given spherical coordinates. The The azimuthal angle theta is in the x-y plane from the negative y-axis, the The polar angle phi is measured from the positive z-axis.
