### ISSUE TITLE
Publishing model checkpoints

### ISSUE THREAD

**Issue by Lurrobert** [One-2-3-45/One-2-3-45#2]
Hello! Thank you for your amazing research

I wonder if you will also publish the **model checkpoints**?

It would make it much more easier to reproduce your tech.

Thanks!

**Comment by Colin97** [comment]
Hello! Thanks for your attention!

Yes, we will release the demo, code, and model checkpoints in the near future!

**Comment by ecumene** [comment]
Can I ask what license the model and code will be?

**Comment by Colin97** [comment]
Probably MIT.

**Comment by xiyufeng2** [comment]
So it uses zero123 to generate novel view img, which is slow and memory-cost. How did you speed it up?

**Comment by Dustinpro** [comment]
We feed inputs in batches and utilize half-precision. We have released the inference code and model checkpoints.
