### ISSUE TITLE
Gradio API inference is broken

### ISSUE THREAD

**Issue by babusi** [One-2-3-45/One-2-3-45#20]
When running the following script:

from gradio_client import Client
client = Client("https://one-2-3-45-one-2-3-45.hf.space")
result = client.predict(
filepath_to_Estimated_elevation_JSON_file,
3,
False,
fn_index=30
)
print(result)

The following error is logged server-side:
FileNotFoundError: [Errno 2] No such file or directory: '.././demo_tmp/tmp_dir/pose.json'

As a result the API does not work on either the official demo or a private space

**Comment by Colin97** [comment]
As mentioned [here](https://huggingface.co/spaces/One-2-3-45/One-2-3-45/discussions/8), the demo interface is designed for interactive GUI use, but not optimized for standalone API calls. Could you follow our instruction to install the environment and download the pre-trained checkpoints?

**Comment by Dustinpro** [comment]
Gradio APIs are now supported. Please refer to the README.md for usage.
