### ISSUE TITLE
Any ways to prevent rescaling when using the demo?

### ISSUE THREAD

**Issue by raywzy** [One-2-3-45/One-2-3-45#23]
Thanks for the great work! I found the input image will somehow be rescaled while using the demo, is there any way to avoid this behavior?

**Comment by Colin97** [comment]
Yes, we rescale the input image to reduce the training and test gap. You can disable it from [here](https://github.com/One-2-3-45/One-2-3-45/blob/2d5b5d03d947022110925ddd16d9b7cebbe485e1/utils/utils.py#L65). However, it may lead to worse results.
