### ISSUE TITLE
Is the generated mesh aligned with the given view coordinate?

### ISSUE THREAD

**Issue by kxhit** [One-2-3-45/One-2-3-45#26]
Hi, great work!
I just tried the both interactive demo and run.py, want to know the generated mesh coordinate system. Is the coordinate (mainly azimuth) aligned with the given view pose? 

I found the coordinate system assumes the given view as the 0 azimuth but the generated mesh is not in the same azimuth. I don't know how to measure the generated mesh against GT mesh if the coordinate is unclear. 

For example, I expect the mesh will be the same coordinate as the give view.
![Screenshot from 2023-10-16 17-37-50](https://github.com/One-2-3-45/One-2-3-45/assets/16812362/32ff2b81-2951-48cd-9c17-9a8f43f82c94)

Please let me know if I missed something. Thanks!

**Comment by Colin97** [comment]
Hi, Thanks for reaching out.

the 0 azimuth refers to the -y direction.

Please refer to the code [here](https://github.com/One-2-3-45/One-2-3-45/blob/3c82aa614fcb80924fddd14531056eda7e795aaa/utils/utils.py#L80).

**Comment by Colin97** [comment]
Thanks for reaching out. The azimuth of the input view is assigned to 30 degrees. For the demo, the coordinate frame is slightly changed for the visualization purpose (please refer to the code [here](https://github.com/One-2-3-45/One-2-3-45/blob/82db7a7e0b2dc7c6040c1f26b674653f2f3112e0/demo/app.py#L359)). Please correct me if there is something wrong. @Dustinpro

**Comment by kxhit** [comment]
Thanks @Colin97 for the prompt reply.

I don't know why the mesh transformation is necessary. But what's your suggestion if I got the generated mesh and I know the c2w between the given view and GT mesh, how I rotate the generated mesh to the same coordinate aligned with GT mesh, so I'm able to do further evaluation?

**Comment by Colin97** [comment]
The 30-degree azimuth is not necessary. The transformation in the gradio demo is mainly for visualization purposes (make the mesh face the user).

I would suggest you first rotate the generated mesh backwards by 30 degrees. Then, you may need to align the axis directions (x-axis, y-axis, etc.) between the generated mesh and your GT mesh. You only need to align one object and then reuse the pose for other objects.

**Comment by kxhit** [comment]
Thanks, it really helps!
