### ISSUE TITLE
Could you please provide access to the evaluation data and code?

### ISSUE THREAD

**Issue by csBob123** [One-2-3-45/One-2-3-45#27]
Dear authors,

Thank you for releasing this fantastic work. Will you provide the evaluation data and code, e.g., the GSO, to calculate the numerical accuracy in the table in your paper?

Thank you so much for your attention.

**Comment by Dustinpro** [comment]
We have released our blender scripts for rendering meshes in evaluation [here](https://github.com/One-2-3-45/One-2-3-45/tree/master/render). For metric calculation, we plan to release them in the repo of our new work, [One-2-3-45++](https://github.com/SUDO-AI-3D/One2345plus).
