### ISSUE TITLE
how to test text-2-3d demo?

### ISSUE THREAD

**Issue by stihuangyuan** [One-2-3-45/One-2-3-45#28]
only find img-2-3d demo, but no text-2-3d demo

**Comment by Dustinpro** [comment]
You can employ publicly available text-to-image models such as DALL-E, Firefly, and SDXL to generate images, which can then be input into our image-to-3D model.

**Comment by Dustinpro** [comment]
We provided the [text-to-3D demo](https://www.sudo.ai/3dgen) in our new work, [One-2-3-45++](https://sudo-ai-3d.github.io/One2345plus_page/). The text-to-image module is engineered to create an image of a single object against a plain background.
