### ISSUE TITLE
colmap data

### ISSUE THREAD

**Issue by limaolin924** [One-2-3-45/One-2-3-45#35]
The model is excellent. Can it input real data from colmap or real multiview data with camera poses for inference and prediction?

**Comment by Dustinpro** [comment]
Our reconstruction model is specifically designed to process multiview images with preset fixed relative poses. It works well with real images, provided their poses align with this setup. However, if the poses in your multiview data significantly deviate from our preset configurations, then our model might not be ideally suited for optimal reconstruction.

**Comment by limaolin924** [comment]
Thank you for your reply!
