### ISSUE TITLE
Multiple images as input

### ISSUE THREAD

**Issue by hadillivvy** [One-2-3-45/One-2-3-45#36]
Can the model be fed multiple images instead of just one to enhance the final 3d model outcome?

**Comment by Dustinpro** [comment]
If the current frozen multi-view prediction module receives multiple images, the resulting predictions, which might not be consistent with each other, are unlikely to enhance the reconstruction quality. However, using multiple images with known poses to further optimize our generated mesh can improve its quality for sure.

**Comment by hadillivvy** [comment]
Thank you for getting back to me @Dustinpro ! Does your implementation support this kind of input (i.e., multiple images with known poses)?

**Comment by Dustinpro** [comment]
We did not implement further optimization in this repo. But you may use our generated mesh as the initial mesh and refine it by leveraging optimization methods that minimize the rendering loss between multiple given images and volume/surface renderings.

**Comment by hadillivvy** [comment]
Hi @Dustinpro you mean by doing something like this https://pytorch3d.org/tutorials/fit_textured_mesh ?

**Comment by Dustinpro** [comment]
No, I mean optimizing a NeRF (e.g., TensoRF. One-2-3-45++ optimizes TensoRF for texture improvement) or mesh (e.g., DMTet. Magic3D optimized DMTet at the refining stage).
