### ISSUE TITLE
Question in training dataset

### ISSUE THREAD

**Issue by Gynjn** [One-2-3-45/One-2-3-45#38]
Thanks for your great work!

I wonder that there is also depth images in dataset. And Did you get them from off-the-shelf depth prediction model?

Thanks.

**Comment by Dustinpro** [comment]
No, we rendered depth images of objects from the Objaverse dataset. A related [issue](https://github.com/One-2-3-45/One-2-3-45/issues/29#issuecomment-1848884728).

**Comment by Gynjn** [comment]
BTW, when you construct 3d cost volume it needs depth of multiple images?
