### ISSUE TITLE
Question regarding training & inference 

### ISSUE THREAD

**Issue by cmh1027** [One-2-3-45/One-2-3-45#45]
![image](https://github.com/One-2-3-45/One-2-3-45/assets/22341329/783adf8c-0153-4f1d-a72d-5dbbeb72e21f)
According to your paper and the code, it seems that the model performs training-inference process unlike traditional test-time optimization of NeRF variants. However, I can't find **which module** is optimized during the training phase.  Zero123 module is frozen during training, and I see that checkpoint of SparseNeus is also provided (maybe this checkpoint is for the 3D convolution module in the figure indicated by the purple color?). Then, which module in the figure is optimized during training?

**Comment by Dustinpro** [comment]
The checkpoint stores [parameters](https://github.com/One-2-3-45/One-2-3-45/blob/master/reconstruction/models/trainer_generic.py#L133) from the 3D Conv and the SDF/RGB MLPs. We train it in our own way.

**Comment by cmh1027** [comment]
then the checkpoint of SparseNeus is the result of your training?

**Comment by Dustinpro** [comment]
> then the checkpoint of SparseNeus is the result of your training?

Yes

**Comment by cmh1027** [comment]
Thanks for reply!
