### ISSUE TITLE
Missing texture of the exported mesh.

### ISSUE THREAD

**Issue by zhangzj1s** [One-2-3-45/One-2-3-45#47]
Hi! execellent work. I'm having trouble exporting a 3D model to OBJ format; the mesh lacks color and texture maps. Despite enabling 'Export Texture Maps,' the issue remains. Can you help me identify any missing settings or steps to ensure textures are included in the OBJ export? I'm just using the intruction: **python run.py --img_path /home/One-2-3-45/demo/demo_examples/00_zero123_lysol.png  --gpu_idx 7 --output_format .obj**  However, i couldn't find any .png which might be texture png  in the exp folder. Any help would be appreciated.
![image](https://github.com/One-2-3-45/One-2-3-45/assets/166377860/4d4a6080-f42c-44ba-b6f4-e87a23b5b668)

**Comment by noureldinabdelalim** [comment]
Hi! Sorry I had an unrelated question, when I finished the installations and tried running the code on colab i faced an issue where torchsparse module is not found. Do you have an idea how i could fix it?

**Comment by Dustinpro** [comment]
The exported .obj files contain vertex colors. You can use Meshlab to view the colors.

**Comment by zhangzj1s** [comment]
> The exported .obj files contain vertex colors. You can use Meshlab to view the colors.

Thanks for your help. Problem is sloved.

**Comment by zhangzj1s** [comment]
> Hi! Sorry I had an unrelated question, when I finished the installations and tried running the code on colab i faced an issue where torchsparse module is not found. Do you have an idea how i could fix it?

Sorry I have no idea about this.
