### ISSUE TITLE
Gradio API down

### ISSUE THREAD

**Issue by cwchenwang** [One-2-3-45/One-2-3-45#49]
![image](https://github.com/One-2-3-45/One-2-3-45/assets/23579918/a6c90ce3-87c3-44e1-abd8-8e4f8e1d5ef7)
Gives me the folloing error:
![image](https://github.com/One-2-3-45/One-2-3-45/assets/23579918/efdf0010-62cc-4c45-b5ba-e0c6676e71cf)

**Comment by Dustinpro** [comment]
The gradio demo environment issue is resolved. The API should work now.
