### ISSUE TITLE
Zero-123-XL

### ISSUE THREAD

**Issue by rlee3359** [One-2-3-45/One-2-3-45#7]
Hi, great work!

With the release of zero-123-xl, swapping in this model should make a significant improvement in results. I'm wondering if the authors have tried this and can report what impact it has. Would it be possible to have the HuggingFace demo upgraded with these weights? I would love to see how much the view diffusion model affects the results.

Thanks!

**Comment by ootts** [comment]
Hi! We have deployed the zero-123-xl model from the release day of our HuggingFace demo. I deel like the performance has improved, producing less shadow on the back side and more consistent multi-view images, but still need to tune and re-generate sometimes.

**Comment by yuedajiong** [comment]
@rlee3359  what is zero-123-XL?  re-train zero-123 on Objaverse-XL?  where?

**Comment by ootts** [comment]
Yes, zero-123-xl is the retrained version of zero123 on objaverse-xl.

**Comment by trltzy** [comment]
wow, how can we update with zero-123-xl?

**Comment by Colin97** [comment]
We have already equipped with the zero-123-xl ckpt. Please follow the instruction to install and download the ckpts.
