### ISSUE TITLE
Multi views export as high resolution?

### ISSUE THREAD

**Issue by mischaschaub** [One-2-3-45/One-2-3-45#8]
Could you provide the feature for exporting the multiview images in a high resolution format? This would be very useful for design work.

**Comment by Dustinpro** [comment]
At present, our model can generate multiview images only at a resolution of 256*256. Feel free to explore our demo, where you can find the multiview images available for download by hovering over the upper right corner of each image.  If you desire higher-resolution images, utilizing an AI image upscaler can be a viable option.

**Comment by mischaschaub** [comment]
Thank you for the quick answer.

**Comment by chris-aeviator** [comment]
@Dustinpro I hadn't found info on this in the paper, did you explore higher resolution as a means to improve mesh quality?

**Comment by One-2-3-45** [comment]
@chris-aeviator The current version of zero123 (multi-view prediction module) only accommodates 256x256 input images. It would be beneficial to have a version that can predict multi-view images at a higher resolution.

**Comment by chris-aeviator** [comment]
@One-2-3-45 understood that,  shouldnt SDF show improvement with higher res mv images (e.g. just upscaled)
