### ISSUE TITLE
Objaverse XL

### ISSUE THREAD

**Issue by mischaschaub** [One-2-3-45/One-2-3-45#9]
Do you plan using objaverse XL in your solution? When might this become available, and how much do you think that this might influence the usefulness of your mesh output?

**Comment by Colin97** [comment]
Yes, we are actively working on enhancing our algorithms and incorporating additional 3D data. Please stay tuned for more updates.

**Comment by mischaschaub** [comment]
Thanks for your answer. I stay tuned with great pleasure and much hope!
